// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextCompactionProgressPhase } from "./ContextCompactionProgressPhase";

export type ContextCompactionProgressNotification = { threadId: string, turnId: string, itemId: string, phase: ContextCompactionProgressPhase, attempt: number, outputBytes: number, outputChunks: number, outputTokens: number | null, };
